baseURL = 'https://blog.sisk-framework.org/'
languageCode = 'en-us'
title = 'Today in Sisk'
theme = 'mini'
publishDir = 'docs'

defaultContentLanguage = "en"

[params]
env = "production"
author = "CypherPotato"
bio = "Talking news, tips and everything else about the Sisk Framework for .NET"
description = "Talking news, tips and everything else about the Sisk Framework for .NET"
# hiddenPostSummaryInHomePage = true
copyright = "Project Principium"

[markup]
  [markup.highlight]
    style = 'vs'