baseURL = 'https://base.sisk-framework.org/'
languageCode = 'en-us'
title = 'Today in Sisk'
theme = 'mini'
publishDir = 'docs'

defaultContentLanguage = "en"

[params]
author = "CypherPotato"
bio = "Talking news, tips and everything else about the Sisk Framework for .NET"
description = "Talking news, tips and everything else about the Sisk Framework for .NET"
# hiddenPostSummaryInHomePage = true
copyright = "Project Principium"
